apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swiggy
  name: swiggy-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
      - name: cont1
        #image: vishnu155/vishnunew:v5
        #image: vishnu155/vishnunew:v6
        image: vishnu155/icerems:latest
        ports:
          - containerPort: 80
